### PR TITLE
Add Xeon kernel support for YU Yureka

### PR DESCRIPTION
**Pull request by SomeshThakur**
downloads : Add support for Xeon kernel for YU Yureka / Yureka+

### CODE REVIEW

**Comment by Grarak** [comment]
Why did you remove Lightning kernel?

**Comment by HridayHS** [comment]
Somesh this is not fair :( By alphabetical order you should keep your kernel Next to me :( I hope you will fix this :). In last commit.

**Comment by SomeshThakur** [comment]
There is no alphabetical order in app :p 
Still i will make your kernel upper :+1:

**Comment by SomeshThakur** [comment]
@Grarak I have added check all commits

**Comment by HridayHS** [comment]
But you know na Your kernel is already is Famous on Forum at least give me a chance at this point. :( By the way It is okay if you want like you can :) I am not forcing you do.

**Comment by SomeshThakur** [comment]
@HridayHS No problem bro !
I have made your kernel upper btw Lightning is quite enough famous :v:

**Comment by Grarak** [comment]
It doesn't matter. KA sorts it alphabetically.

**Comment by SomeshThakur** [comment]
@Grarak LOL! Though i had made it upper :)

**Comment by Grarak** [comment]
Your json file is full of missing ",".

**Comment by HridayHS** [comment]
Like -,- Hehe

**Comment by SomeshThakur** [comment]
Yeah just now noticed 
My bad
Adding just a min

**Comment by SomeshThakur** [comment]
@Grarak Now check all done

**Comment by bishnuprasad884uu** [comment]
I want to add my new kernel

**Comment by HridayHS** [comment]
Which new Kernel ? Dare or other ?

**Comment by bishnuprasad884uu** [comment]
New version of Dare - Eximious

**Pull request merged**
