### PR TITLE
Card-ify I/O Scheduler fragment

### PR DESCRIPTION
**Pull request by boswelja**
* And update build.gradle versions

### CODE REVIEW

**Comment by Grarak** [comment]
too many views in a card will decrease performance.
settings should be at the bottom.
and don't use sdk 24

**Comment by boswelja** [comment]
K then, guess I'll have to do my own personal builds to be satisfied..
Why should settings be at the bottom? Every other app I've ever used has stuff like faq/about after settings

**Comment by Grarak** [comment]
Well if settings should be the first then put about and contributors into settings. Will rewrite few things

**Comment by Grarak** [comment]
I would put every major setting into cards, but simply not possible without decreasing performance.
Might require a rewrite of cardview.
Latest sdk breaks dialog on some devices. Also fragments behave weird. Causing fcs on some devices.

**Comment by boswelja** [comment]
If a device can't handle a few cardviews, somethings wrong.
As for using the latest sdk, I'm surprised.

**Comment by Grarak** [comment]
It's not a few cardviews. It's one cardview with too many views.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/8c04c80d44aa0d6d1cb4ccb8789b01afd4b7de47

**Pull request closed without merging**
