### PR TITLE
screen: add mdss_fb backlight_dimmer option

### PR DESCRIPTION
**Pull request by chrisc93**
Adds a checkbox for mdss_fb backlight_dimmer parameter in the elementalX kernel for the Nexus 5X (and possibly others too).

### CODE REVIEW

**Comment by Grarak** [comment]
Backlight dimmer is already supported. Look at MSM_BACKLIGHT_DIMMER

**Comment by chrisc93** [comment]
Right, I saw that. But Aaron Segaert implemented the backlight dimmer option to use a mdss_fb parameter since the Nexus 5X doesn't have the msm_backlight feature

**Comment by javelinanddart** [comment]
@grarak MSM_BACKLIGHT_DIMMER is for MDP devices/MDP 4 and under
this is for MDSS devices aka MDP 5 and up it look like

**Comment by Shoaib0597** [comment]
@Grarak, will you merge this? It is quite important. :) Without this, the option doesn't shows up in Adiutor.

**Pull request merged**
