### PR TITLE
Logger: Add Additional Sysfs

### PR DESCRIPTION
**Pull request by javelinanddart**
Change-Id: Iec55ff525ba733f4ebda514dfa4f6b537f653202
Signed-off-by: Paul Keith <javelinanddart@gmail.com>

### CODE REVIEW

**Comment by javelinanddart** [comment]
Hmm
says build failed
Closing

**Comment by Tsunamical** [comment]
It says build failing because the travis has yet to include 23.0.2 build tools, your commit was correct

**Comment by javelinanddart** [comment]
@Tsunamical Thanks for the notice

**Comment by Tsunamical** [comment]
No prob :)

**Pull request merged**
