### PR TITLE
intelli_plug: Add InSaNiTy Profiles

### PR DESCRIPTION
**Pull request by javelinanddart**
* Relevant Kernel Change is here: https://github.com/CandyDevices/kernel_samsung_jf/commit/48e908ae5184b5add592b3750b2bd60b99051bfc

### CODE REVIEW

**Comment by Grarak** [comment]
This will break other intelliplug implementations

**Comment by javelinanddart** [comment]
How?

**Comment by Tsunamical** [comment]
It implies all intelliplug implementations have insanity profiles.

**Comment by javelinanddart** [comment]
The code? I linked to kernel commit so if people wanted to find it they
could. If there's an issue with the Java, then let me know

**Comment by Tsunamical** [comment]
Fact is, by doing this every other intelliplug implementation would need to implement this or else kernel adiutor wouldn't work with it. It's minority vs majority. Bump the version and do a version check or something so not every implementation has to make accommodations.

**Comment by javelinanddart** [comment]
Will add as a feature request after bumping version number

**Pull request closed without merging**
