### PR TITLE
[Misc] Add support for wlan ctrl wakelock divider

### PR DESCRIPTION
**Pull request by vt0r**
Several kernels have the ability to control the WLAN Ctrl wakelocks in the same manner as the WLAN RX ones. This PR adds support for the sysfs node that's most commonly used.

### CODE REVIEW

**Comment by Grarak** [comment]
There is no toggle for it

**Comment by vt0r** [comment]
Sorry, but I don't understand, @Grarak . Where should there be a toggle? The sysfs node only accepts an integer value.

**Comment by Grarak** [comment]
there is no UI to control this

**Comment by vt0r** [comment]
Oh whoops. I assumed there was logic to create the UI item based on the contents. I'll dig through and find the UI spot and add it to this PR

**Comment by vt0r** [comment]
Sorry for the delay here. I've finally found the time to come back to this, and I've added the missing UI slider I neglected earlier. I built this with `assembleDebug`, and the slider works as expected. I only updated the primary string for this new value, but I think I can translate at least two other languages for that value. Are you using Transifex or something similar, or should I contribute translations directly to the codebase?

**Comment by vt0r** [comment]
Also squashed my two commits into one. If you want me to commit the translations I can in this PR, let me know, otherwise, please point me to the Transifex or similar project, and I'll contribute some there.

**Comment by vt0r** [comment]
Is there any way to force Travis CI to rebuild this? Built without issue on my end - no extra warnings or anything either.

**Pull request merged**
