### PR TITLE
Update tomato.json with Velocity Kernel

### PR DESCRIPTION
**Pull request by Shoaib0597**

### CODE REVIEW

**Comment by Grarak** [comment]
Your json is full of errors

**Comment by Shoaib0597** [comment]
In Features section or everywhere. :P

**Comment by Shoaib0597** [comment]
By they way, I'll try to correct all of it. :) It would be great to get my kernel listed in your app. Afterall, Kernel Adiutor is the best Kernel-Management app that I have come across in Google Play. Keep doing your awesome work. :)

**Comment by Shoaib0597** [comment]
Hey, I think I have fixed my tomato.json completely now as jSON Editor Online didn't report any errors! :)

A small request to you---
 When you add my kernel, it would be great if you mention my name in the ChangeLogs of Kernel Adiutor.
 For ex--
 Added Download Support for Velocity Kernel by Shoaib Anwar.

Thanks!

**Comment by Shoaib0597** [comment]
Thank You @Grarak :)

**Pull request merged**
