### PR TITLE
misc: Fix Broken Fsync Toggle

### PR DESCRIPTION
**Pull request by javelinanddart**
* The toggle starts off saying Fsync is off no matter what
* This should fix that issue and show the correct fsync status

### CODE REVIEW

**Comment by Grarak** [comment]
Older implementation still use 1 and 0

**Comment by Tsunamical** [comment]
Yeah, that was something I added in my initial commit but then rebased since someone said that 1 and Y implied the same value. I'll create a new pr to address the two different strings based off my first pr.

**Comment by javelinanddart** [comment]
I have yet to see an implementation with 1 and 0, could either of you point
me to one?

**Comment by yoinx** [comment]
The Y/N parameter is a result of the driver using the built-in moduleparam calls vice direct sysfs functions.  When writing the value   the moduleparam function will change a 1 to a Y.  However,  on the get side in ka it typically only checks for a equals("1"). You need to change this to not return the equals result,  and instead check for either a 1 or a Y to return true to allow for either situation.

**Comment by Tsunamical** [comment]
Can be closed now

**Comment by javelinanddart** [comment]
oh ya
thanks

**Pull request closed without merging**
