### PR TITLE
Mass Merge

### PR DESCRIPTION
**Pull request by javelinanddart**

### CODE REVIEW

**Comment by javelinanddart** [comment]
Pushed a few more

**Comment by javelinanddart** [comment]
Force Pushed a Derp fix

**Comment by javelinanddart** [comment]
OK, rebased, cleaned up, should build now

**Comment by javelinanddart** [comment]
Yep, builds
It should be good to go

**Comment by Grarak** [comment]
Please don't put everything in one pull request

**Comment by javelinanddart** [comment]
*sighs* pull requested them all individually

**Pull request closed without merging**
