### PR TITLE
fix wrong author for zen decision

### PR DESCRIPTION
**Pull request by Tkkg1994**
Zen decision was not developed by alucard, instead it was by bbedward!

### CODE REVIEW

**Comment by Grarak** [comment]
Please change the english translation

**Comment by Tkkg1994** [comment]
In english it is already correct. No idea why it is different in german. But in english language there is the right author

**Comment by Grarak** [comment]
Then please change it in crowdin

**Comment by Tsunamical** [comment]
Fixed in https://github.com/Grarak/KernelAdiutor/commit/71d7d8e95e7725af38f4d9a7cae012f58d29de74

@Tkkg1994

**Comment by Tkkg1994** [comment]
Thank you man :+1:

**Pull request closed without merging**
